<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<li><a href="<spring:url value="/"/>"><spring:message code="home.page"></spring:message></a></li>
<li><a href="<spring:url value="/ProductBackLogReleases/create"/>"><spring:message code="ReleaseBacklogsReleases.create.menu"></spring:message></a></li>
<li><a href="<spring:url value="/ProductBackLogReleases/list"/>"><spring:message code="ReleaseBacklogsReleases.edit.menu"></spring:message></a></li>
<li><a href="<spring:url value="/ProductBackLogReleases/list"/>"><spring:message code="ReleaseBacklogsReleases.list.menu"></spring:message></a></li>
<li><a href="<spring:url value="/sprints/"/>"><spring:message code="sprint.menu"></spring:message></a></li>
<li><a href="<spring:url value="/userStorys/"/>"><spring:message code="user.story.menu"></spring:message></a></li>
<!--<li><a href="<spring:url value="#"/>"><spring:message code="projects"></spring:message></a></li>-->
<li><a href="<spring:url value="/proccessLogout"/>"><spring:message code="logout"></spring:message></a></li>